/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screens;




import java.io.File;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
//import javax.xml.bind.JAXBException;

import javax.xml.bind.Unmarshaller;
import xml.Restaurant;
import xml.Table;
import xml.UserLoad;
/**
 *
 * @author LENOVO
 */
public class ClientForm extends javax.swing.JFrame {
Restaurant restaurant;
//Reservations reservation;
int reservedTableNumber;
String customerName;
    /**
     * Creates new form clientForm
     */
    List<Table> tablesList;
    public ClientForm(Restaurant restaurant, String customerName) throws JAXBException   {
        this.tablesList=restaurant.getTables().getTables();
        initComponents();
        //readXMLtables();
        this.restaurant=restaurant;
        this.customerName=customerName;
        
        
    }
    private void readXMLtables() throws JAXBException{
        JAXBContext jaxbcontext = JAXBContext.newInstance(Restaurant.class);
        Unmarshaller u=jaxbcontext.createUnmarshaller();
        restaurant = (Restaurant) u.unmarshal(new File("data.xml"));
        List<Table>list = restaurant.getTables().getTables();
    }
     private void saveXMLtables() throws JAXBException{
        JAXBContext jaxbcontext = JAXBContext.newInstance(Restaurant.class);
         Marshaller   u=jaxbcontext.createMarshaller();
       u.marshal(restaurant,new File("data.xml"));
      //  List<Tableload>list = restaurant.getTables().getTables();
    }
  
   
        
   // }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Smoking_Box = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        nOfSeats = new javax.swing.JComboBox<>();

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 153));
        jLabel11.setText("Please enter the date and time you want to reserve a table in:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("We are pleased to serve you!");

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 204));
        jLabel2.setText("Which area do you prefer?");

        Smoking_Box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Smoking", "Non-smoking" }));
        Smoking_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Smoking_BoxActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 204));
        jLabel4.setText("Please choose the number of seats you want to reserve:");

        jButton1.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 204));
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 0, 204));
        jButton2.setText("Continue");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        nOfSeats.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4", "5", "6", "7", "12" }));
        nOfSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nOfSeatsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(19, 19, 19))))
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(Smoking_Box, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 133, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(nOfSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Smoking_Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nOfSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Smoking_BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Smoking_BoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Smoking_BoxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String area=Smoking_Box.getSelectedItem().toString();
      //  String sseats=nseats_S.getSelectedItem().toString();
      //  int smokingseats=Integer.parseInt(sseats);
      //  String nseats=nseats_N.getSelectedItem().toString();
      //  int nonsmokingseats=Integer.parseInt(nseats);
       String seats=  nOfSeats.getSelectedItem().toString();
       int nSeats=Integer.parseInt(seats);
               if(area.equals("Smoking")){
                   if((nSeats!=4)&&(nSeats!=6)&&(nSeats!=7)&&(nSeats!=12)){
                       JOptionPane.showMessageDialog(rootPane,"Error! This table does not exist.");
                   }
                   else{
                       int found =0;
                       for(int i=0; i<tablesList.size();i++){
                if(tablesList.get(i).isSmoking()==true&&tablesList.get(i).getNumber_of_seats()==nSeats&&tablesList.get(i).isReserved()==false){
                    tablesList.get(i).setReserved(true);
                    found=1;
                    reservedTableNumber=tablesList.get(i).getNumber();
                    ClientForm2 cc;
                    try {
                        cc = new ClientForm2(restaurant, reservedTableNumber, customerName);
                        cc.setVisible(true);
                        this.setVisible(false);
                    } catch (JAXBException ex) {
                        Logger.getLogger(ClientForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                   
                }
                
            
        }
            if (found==0){
                JOptionPane.showMessageDialog(rootPane, "This table is reserved, please try again later or choose another table.");
            }
                   }
               }
               else if(area.equals("Non-smoking")){
                   if((nSeats!=4)&&(nSeats!=5)&&(nSeats!=12)){
                       JOptionPane.showMessageDialog(rootPane,"Error! This table does not exist.");
                   }
                   else{
                       int found =0;
                       for(int i=0; i<tablesList.size();i++){
                if(tablesList.get(i).isSmoking()==false&&tablesList.get(i).getNumber_of_seats()==nSeats&&tablesList.get(i).isReserved()==false){
                    tablesList.get(i).setReserved(true);
                    found=1;
                    reservedTableNumber=tablesList.get(i).getNumber();
                    ClientForm2 cc;
                    try {
                        cc = new ClientForm2(restaurant, reservedTableNumber, customerName);
                        cc.setVisible(true);
                        this.setVisible(false);
                    } catch (JAXBException ex) {
                        Logger.getLogger(ClientForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                   
                }
                
            
        }
            if (found==0){
                JOptionPane.showMessageDialog(rootPane, "This table is reserved, please try again later or choose another table.");
            }
                   }
               }
           
               
      
        
       
    try {
        saveXMLtables();
    } catch (JAXBException ex) {
        Logger.getLogger(ClientForm.class.getName()).log(Level.SEVERE, null, ex);
    }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Login LForm;
    try {
        LForm = new Login();
        LForm.setVisible(true);
        this.setVisible(false);
    } catch (JAXBException ex) {
        Logger.getLogger(ClientForm.class.getName()).log(Level.SEVERE, null, ex);
    }

   
       
   
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nOfSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nOfSeatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nOfSeatsActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Smoking_Box;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> nOfSeats;
    // End of variables declaration//GEN-END:variables
}
