/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screens;


import java.io.File;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Unmarshaller;
import xml.Dish;
import xml.Order;
import xml.Reservations;
import xml.Restaurant;


/**
 *
 * @author LENOVO
 */
public class CookerForm extends javax.swing.JFrame {
Reservations reservation;
List<Order> list;
 StringBuilder ordersStr = new StringBuilder();

    /**
     * Creates new form CookerForm
     */
private void readOrdersXML() throws JAXBException{
        JAXBContext jaxbcontext = JAXBContext.newInstance(Reservations.class);
        Unmarshaller u=jaxbcontext.createUnmarshaller();
        reservation = (Reservations) u.unmarshal(new File("Orders.xml"));
    
}
    public CookerForm(Reservations reservation) throws JAXBException {
        initComponents();
        readOrdersXML();
        this.list=reservation.getOrders().getOrder();
        
        for(int i=0;i<list.size();i++){
     
            ordersStr.append("  ").append("Order Number: ");
            ordersStr.append("  ").append(i+1);
            ordersStr.append(System.getProperty("line.separator")); 
            ordersStr.append("      ").append("Table Number: ");
            ordersStr.append("  ").append(String.valueOf(list.get(i).getTableNumber()));
            ordersStr.append(System.getProperty("line.separator"));  
            ordersStr.append("      ").append("Ordered Dishes: ");
            ordersStr.append(System.getProperty("line.separator"));
            for(int j=0;j<list.get(i).getDishes().size();j++){
                ordersStr.append("      ").append("Dish ").append(j+1).append(".");
                ordersStr.append(System.getProperty("line.separator")); 
                ordersStr.append("        ").append("Dish Quantity: ");
                ordersStr.append("  ").append(String.valueOf(list.get(i).getDishes().get(j).getQuantity()));
                ordersStr.append(System.getProperty("line.separator"));
                ordersStr.append("        ").append("Dish Name: ");
                ordersStr.append("  ").append(list.get(i).getDishes().get(j).getName());
                ordersStr.append(System.getProperty("line.separator")); 
                ordersStr.append("        ").append("Dish Type: ");
                ordersStr.append("  ").append(list.get(i).getDishes().get(j).getType());
                ordersStr.append(System.getProperty("line.separator")); 
                
                
            }
              
            ordersStr.append("==================================");
            ordersStr.append("==================================");
            ordersStr.append(System.getProperty("line.separator"));
    }
 
        jTextArea1.setLineWrap(true);
        jTextArea1.setText(ordersStr.toString());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu_label = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        menu_label1 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu_label.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        menu_label.setForeground(new java.awt.Color(102, 102, 255));
        menu_label.setText("Ordered meals for today are:");

        jButton1.setFont(new java.awt.Font("Segoe Print", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 0, 204));
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        menu_label1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        menu_label1.setForeground(new java.awt.Color(0, 0, 204));
        menu_label1.setText("Good luck!");

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 255), new java.awt.Color(153, 153, 255), new java.awt.Color(102, 51, 255), null));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(menu_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(menu_label, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu_label)
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menu_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login LForm;
    try {
        LForm = new Login();
         LForm.setVisible(true);
        this.setVisible(false);
    } catch (JAXBException ex) {
        Logger.getLogger(CookerForm.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel menu_label;
    private javax.swing.JLabel menu_label1;
    // End of variables declaration//GEN-END:variables
}
