/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screens;

import java.util.List;
import xml.Order;

/**
 *
 * @author Sony
 */
public class ManagerReservations extends javax.swing.JFrame {

    /**
     * Creates new form ManagerReservations
     */
    
    StringBuilder ordersStr = new StringBuilder();
    
    public ManagerReservations(List <Order> ordersList) {
        initComponents();
        printOrdersList(ordersList);
         jTextArea1.setLineWrap(true);
         jTextArea1.setText(ordersStr.toString());
        
    }

    private void printOrdersList(List <Order> ordersList){
    int i;
    int p;
    int q;
    int dp=0;
    for(i=0;i<ordersList.size();i++){
     
            ordersStr.append("  ").append(i+1).append(".");
            ordersStr.append("  ").append("Order Number: ");
            ordersStr.append("  ").append(i+1);
            ordersStr.append(System.getProperty("line.separator")); 
            ordersStr.append("      ").append("Table Number: ");
            ordersStr.append("  ").append(String.valueOf(ordersList.get(i).getTableNumber()));
            ordersStr.append(System.getProperty("line.separator")); 
            ordersStr.append("      ").append("Customer Name: ");
            ordersStr.append("  ").append(ordersList.get(i).getCustomerName());
            ordersStr.append(System.getProperty("line.separator")); 
            ordersStr.append("      ").append("Ordered Dishes: ");
            ordersStr.append(System.getProperty("line.separator"));
            for(int j=0;j<ordersList.get(i).getDishes().size();j++){
                ordersStr.append("      ").append("Dish ").append(j+1).append(".");
                ordersStr.append(System.getProperty("line.separator")); 
                ordersStr.append("        ").append("Dish Name: ");
                ordersStr.append("  ").append(ordersList.get(i).getDishes().get(j).getName());
                ordersStr.append(System.getProperty("line.separator")); 
                ordersStr.append("        ").append("Dish Type: ");
                ordersStr.append("  ").append(ordersList.get(i).getDishes().get(j).getType());
                ordersStr.append(System.getProperty("line.separator")); 
                ordersStr.append("        ").append("Dish Price: ");
                ordersStr.append("  ").append(String.valueOf(ordersList.get(i).getDishes().get(j).getPrice()));
                ordersStr.append(System.getProperty("line.separator")); 
                ordersStr.append("        ").append("Dish Quantity: ");
                ordersStr.append("  ").append(String.valueOf(ordersList.get(i).getDishes().get(j).getQuantity()));
                ordersStr.append(System.getProperty("line.separator"));  
                p = ordersList.get(i).getDishes().get(j).getPrice();
                q = ordersList.get(i).getDishes().get(j).getQuantity();
                dp=dp+(p*q);
                
            }
                ordersStr.append("        ").append("**Order Bill**: ");
                ordersStr.append("  ").append(String.valueOf(dp));
                ordersStr.append(System.getProperty("line.separator")); 
                ordersStr.append("        ").append("**Order Bill after Taxes**: ");
                ordersStr.append("  ").append(String.valueOf(ordersList.get(i).getOrderBill()));
                ordersStr.append(System.getProperty("line.separator")); 
                ordersStr.append("----------------------------------");
                ordersStr.append(System.getProperty("line.separator")); 
                dp=0;
            ordersStr.append("==================================");
            ordersStr.append("==================================");
    }
}   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        label1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(153, 153, 255), null));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );

        label1.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(0, 51, 153));
        label1.setText("Reservations");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
